### ISSUE TITLE
Subcommand to just show the location of a package

### ISSUE THREAD

**Issue by nisanth074** [adamsanderson/qwandry#36]
Hi,

I use `bundle show` a lot to find a gem's location (so I can subsequently cd into it and grep). It'd nice to be able to do the same in qwandry.
```
qw show some_gem
# Prints the gem's location
```
Let me know if this is acceptable, I'll try sending a PR. Thanks.

**Comment by adamsanderson** [comment]
Perhaps if it were a flag? `qw --show some_gem`
Otherwise people might get unexpected behavior if they were searching for a
gem named something like "showtime" and typed in `qw show`.

On Mon, May 18, 2015 at 11:19 AM, Nisanth Chunduru <notifications@github.com

**Comment by nisanth074** [comment]
Ah, didn't realize that qwandry supported partial package names. Should have read the README more carefully.

Here's the pull https://github.com/adamsanderson/qwandry/pull/37/
